AWSTemplateFormatVersion: 2010-09-09
Description: website s3 bucket stack

Metadata:
  AWS::Cloudformation::Interface:
    Parametergroups:
      - Label:
          default: API
        Parameters:
          - ApiStageName
          - AccessLogRetentionInDays
          - FunctionMemorySize
          - FunctionTimeout
          - FunctionLogRetentionInDays
          - UpsertSalesTaxesTotalPriceHandlerName

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref S3Bucket
                - /*
  DNS:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Join
        - ''
        - - !Ref HostedZoneName
          - '.'
      Comment: Add CName to point to S3 bucket endpoint.
      RecordSets:
      -
        Name: !Ref BucketName
        Type: CNAME
        TTL: 900
        ResourceRecords:
        - !Join ['', !Split ['http://', !GetAtt S3Bucket.WebsiteURL ]]

Outputs:
  WebsiteURL:
    Description: URL for website hosted on S3
    Value: !GetAtt
      - S3Bucket
      - WebsiteURL
