AWSTemplateFormatVersion: 2010-09-09
Description: website s3 bucket stack

Metadata:
  AWS::Cloudformation::Interface:
    Parametergroups:
      - Label:
          default: Storage
        Parameters:
          - BucketName
      - Label:
          default: DNS
        Parameters:
          - HostedZoneName

Parameters:
  BucketName:
    Description: Name of the S3 bucket hosting the website
    Type: String
    Default: test.icydigital.com

  HostedZoneName:
    Description: Name of the hosted zone
    Type: String
    Default: icydigital.com

Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref WebsiteBucket
                - /*
  HostedZone:
    Type: "AWS::Route53::HostedZone"
    Properties:
      HostedZoneConfig:
        Comment: 'My hosted zone for icydigital.com'
      Name: !Ref HostedZoneName

  DNS:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Ref HostedZoneName
      Comment: Add CName to point to S3 bucket endpoint
      RecordSets:
      -
        Name: !Ref BucketName
        Type: CNAME
        TTL: 900
        ResourceRecords:
        - !Join ['', !Split ['http://', !GetAtt WebsiteBucket.WebsiteURL ]]

Outputs:
  WebsiteURL:
    Description: URL for website hosted on S3
    Value: !GetAtt
      - WebsiteBucket
      - WebsiteURL
