name: cx

on: push

env:
  AWS_REGION: us-east-1
  API_STAGE_NAME: "v0"
  ACCESS_LOG_RETENTION_DAYS: 7
  FUNC_MEMORY_SIZE: 128
  FUNC_TIMEOUT: 5
  FUNC_LOG_RETENTION_DAYS: 7

defaults:
  run:
    shell: "/bin/bash {0}"

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      CFN_TEMPLATES: "./api-gateway/stack.yml\n.github/cd_setup.yml\n"
    steps:
      - name: clone the repo
        uses: actions/checkout@v2.3.4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.5.3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: validate all cloudformation templates
        run: |
          printf "${{ env.CFN_TEMPLATES }}" | while read template; do
            aws cloudformation validate-template \
              --template-body="file://$template"
          done

  deploy:
    runs-on: ubuntu-latest
    needs: validate
    outputs:
      _stack_name: ${{ steps.configure_environment.outputs._stack_name }}
    steps:
      - name: clone the repo
        uses: actions/checkout@v2.3.4

      - name: map branch 2 test/prod
        run: |
          if [[ ${{ github.ref }} == *main ]]; then
            echo "ENVIRONMENT=test" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=test" >> $GITHUB_ENV
          fi

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.5.3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: configure the environment
        id: configure_environment
        run: |
          echo "STACK_NAME=sample-api-$ENVIRONMENT" >> $GITHUB_ENV
          echo "READ_SALES_TAXES_TOTAL_PRICE_NAME=sample-api-$ENVIRONMENT-readsalestaxestotalpricehandler" >> $GITHUB_ENV
          echo "::set-output name=_stack_name::sample-api-$ENVIRONMENT"

      - name: deploy the api gateway stack
        run: |
          aws cloudformation deploy \
            --template-file=./api-gateway/stack.yml \
            --stack-name=${{ env.STACK_NAME }} \
            --parameter-overrides \
              Environment=${{ env.ENVIRONMENT }} \
              ApiStageName=${{ env.API_STAGE_NAME }} \
              FunctionMemorySize=${{ env.FUNC_MEMORY_SIZE }} \
              FunctionTimeout=${{ env.FUNC_TIMEOUT}} \
              FunctionLogRetentionInDays=${{ env.FUNC_LOG_RETENTION_DAYS }} \
              AccessLogRetentionInDays=${{ env.ACCESS_LOG_RETENTION_DAYS }} \
              ReadSalesTaxesTotalPriceHandlerName=${{ env.READ_SALES_TAXES_TOTAL_PRICE_NAME }} \
            --capabilities=CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset

      - name: deploy the lambda handler
        run: |
          cd ./api-gateway/lambdas/receipt/read && npm ci && ls
          tsc
          cd / && ls -R
          [ -f "index.js" ] && echo "compilation completed!" || exit 1
